# Generated by Django 4.2.5 on 2023-09-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='type',
        ),
    ]
